# Generated by Django 2.1.7 on 2019-03-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='block',
            field=models.CharField(blank=True, choices=[('at', 'Atoms'), ('as', 'Atomic States'), ('mo', 'Molecules'), ('ms', 'Molecular States'), ('mq', 'Molecular Quantum Numbers'), ('ct', 'Collisional Transitions'), ('rt', 'Radiative Transitions'), ('nr', 'Non-Radiative Transitions'), ('me', 'Methods'), ('fu', 'Functions'), ('en', 'Environments'), ('so', 'Sources'), ('sd', 'Solids'), ('pa', 'Particles')], max_length=2, null=True, verbose_name='XSAMS block'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='constr',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Constraint'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='datatype',
            field=models.BooleanField(default=False, verbose_name='DataType in XSAMS?'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='ldescr',
            field=models.TextField(verbose_name='Long description'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='sdescr',
            field=models.TextField(verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='type',
            field=models.CharField(blank=True, choices=[('s', 'String'), ('i', 'Integer'), ('f', 'Float'), ('b', 'Boolean')], max_length=1, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='unit',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='usage',
            field=models.ManyToManyField(blank=True, to='browse.Usage'),
        ),
    ]
